- name: Build and push frontend
  uses: docker/build-push-action@v5
  with:
    context: ./frontend
    push: true
    platforms: linux/arm64
    tags: |
      ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
      ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.sha_short }}

- name: Build and push backend
  uses: docker/build-push-action@v5
  with:
    context: ./backend
    push: true
    platforms: linux/arm64
    tags: |
      ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
      ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.vars.outputs.sha_short }}

- name: Build and push nginx
  uses: docker/build-push-action@v5
  with:
    context: ./nginx
    push: true
    platforms: linux/arm64
    tags: |
      ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
      ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ steps.vars.outputs.sha_short }}
